name: Build & Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, push Docker image
      run: |
        IMAGE_TAG=latest
        REPO=794038231671.dkr.ecr.ap-southeast-2.amazonaws.com/my-mlflow-app
        docker build -t $REPO:$IMAGE_TAG .
        docker push $REPO:$IMAGE_TAG

    - name: Update ECS service
      run: |
        aws ecs update-service \
          --cluster my-ml-cluster \
          --service my-ml-service \
          --force-new-deployment
